version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - ghkim3221
  assignees:
  - ghkim3221
  ignore:
  - dependency-name: "@theme-ui/prism"
    versions:
    - 0.7.2
  - dependency-name: gatsby
    versions:
    - 2.32.6
